_1. Import numpy as np and see the version_

In [2]:
import numpy as np
print(np.__version__)

1.14.3


_2. Create a 1D array_

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

_3. Create a boolean array_

In [3]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

_4. Extract items that satisfy a given condition from 1D array_

In [9]:
# Input
arr = np.array([0,1,2,3,4,5,6,7,8,9])

# Solution
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

_5. Replace items that satisfy a condition with another value in numpy array_

In [21]:
# Input
arr = np.array([0,1,2,3,4,5,6,7,8,9])

# Solution
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

_6. Replace items that satisfy a condition without affecting the original array_

In [20]:
# Solution
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

_7. Convert a 1D array to a 2D array with 2 rows_

In [23]:
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

_8. Stack arrays a and b vertically_

In [26]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

print(np.concatenate([a, b], axis=0))

print(np.vstack([a, b]))

print(np.r_[a, b])

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


_9. Stack the arrays a and b horizontally_

In [27]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

print(np.concatenate([a, b], axis=1))

print(np.hstack([a, b]))

print(np.c_[a, b])

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


_10. Create the following pattern without hardcoding. UIse only numpy functions and the below input array a._

In [30]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

_11. Get the common items between a and b_

In [31]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

_12. From array a remove all items present in array b_

In [35]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

_13. Get the positions where elements of a and b match_

In [36]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

_14. Get all items between 5 and 10 from a_

In [41]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

index = np.where((a>= 5) & (a <= 10))
print(a[index])

index = np.where(np.logical_and(a>=5, a<=10))
print(a[index])

a[(a>=5) & (a <=10)]


[ 6  9 10]
[ 6  9 10]


array([ 6,  9, 10])

_15. Convert the function maxx that works on two scalars, to work on two arrays_

In [44]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
    
pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

_16. Swap columns 1 and 2 in the array arr._

In [48]:
arr = np.arange(9).reshape(3,3)
arr
print(arr[:, [1,0,2]])

arr[:, [2,0,1]]

[[1 0 2]
 [4 3 5]
 [7 6 8]]


array([[2, 0, 1],
       [5, 3, 4],
       [8, 6, 7]])

_17. Swap rows 1 and 2 in the array arr_

In [51]:
arr = np.arange(9).reshape(3,3)
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

_18. Reverse the rows of a 2D array arr_

In [52]:
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

_19. Reverse the columns of a 2D array arr._

In [54]:
arr = np.arange(9).reshape(3,3)
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

_20. Create a 2D array of shape 5x3 tp contain random decimal numbers between 5 and 10._

In [57]:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)

rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[9.09829505 9.99927246 7.02050753]
 [9.34652887 6.79578658 6.01581862]
 [9.21814071 5.3501688  6.04875079]
 [8.19956489 6.78222543 7.74759569]
 [7.44766264 6.54747944 7.89307464]]
[[8.66435256 6.13832525 9.78431726]
 [7.8481192  6.80164543 6.82739201]
 [8.92456636 9.57425642 6.53617397]
 [5.299029   5.01991092 8.6801392 ]
 [7.34604405 5.71015405 9.17664137]]


_21. Print or show only 3 decimal places of the numpy array rand_arr_

In [71]:
rand_arr = np.random.random((5,3))

np.set_printoptions(precision=3)
rand_arr[:5]

array([[0.852, 0.337, 0.846],
       [0.75 , 0.23 , 0.797],
       [0.424, 0.384, 0.863],
       [0.743, 0.827, 0.848],
       [0.594, 0.643, 0.816]])

_22. Pretty print rand_arr by suppressing the scientific notation (like 1e10)_

In [76]:
np.set_printoptions(suppress=False)
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)

np.set_printoptions(suppress=True, precision=6) 
rand_arr

[[5.434049e-04 2.783694e-04 4.245176e-04]
 [8.447761e-04 4.718856e-06 1.215691e-04]
 [6.707491e-04 8.258528e-04 1.367066e-04]]


array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

_23. Limit the number of items printed in python numpy array a to maximum of 6 elements._

In [77]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

_24. Print the full numpy array a without truncating_

In [80]:
np.set_printoptions(threshold=np.nan)
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

_25. Import the iris dataset keeping the text intact_

In [3]:
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)